### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by emma-campbell** [emma-campbell/dotfiles#3]
# To-Do
- [ ] Modify Custom Plugins
- [ ] Update installation instructions
- [ ] Add to inspirations/rescources
- [ ] Link other cool dotfiles & spread the wealth of knowledge
